
name: Build and Publish XBPS Repository

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            curl \
            xz-utils \
            bash


      - name: Install static XBPS
        run: |
          curl -L \
            https://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz \

      - name: Create XBPS repository
        run: |
          mkdir -p repo

          find void-packages/hostdir/binpkgs \
            -name "*.xbps" \
            -exec cp {} repo/ \;

          touch repo/.nojekyll

